import type { MemberSnapshot } from "@/application/member/contracts";
import { addDays, dayKey } from "@/shared/lib/date";

export function createSeed(): MemberSnapshot {
  const today = dayKey();
  const sessions = [
    [
      "yoga",
      "Basic Yoga",
      "Yoga",
      "linh",
      "Ling Ling",
      "Studio A",
      1,
      "18:30",
      "19:30",
      16,
      20,
    ],
    [
      "strength",
      "Basic Body",
      "Fitness",
      "alex",
      "Alex Morgan",
      "Gym Room",
      2,
      "17:00",
      "18:00",
      14,
      20,
    ],
    [
      "groupx",
      "GroupX",
      "GroupX",
      "linh",
      "Ling Ling",
      "Studio B",
      3,
      "07:00",
      "08:00",
      12,
      12,
    ],
    [
      "stretch",
      "& Recovery muscles",
      "Fitness",
      "alex",
      "Alex Morgan",
      "Studio A",
      4,
      "18:00",
      "19:00",
      8,
      16,
    ],
    [
      "yoga-next",
      "Basic Yoga",
      "Yoga",
      "linh",
      "Ling Ling",
      "Studio A",
      8,
      "18:30",
      "19:30",
      10,
      20,
    ],
  ] as const;
  return {
    version: 1,
    profile: {
      id: "demo-member",
      fullName: "Philosophy",
      email: "minhtriet@example.com",
      phone: "",
      goal: "Extensive Power",
      level: "Beginner",
    },
    sessions: sessions.map(
      ([
        id,
        name,
        discipline,
        coachId,
        coachName,
        room,
        offset,
        start,
        end,
        confirmedCount,
        capacity,
      ]) => ({
        id,
        name,
        discipline,
        coachId,
        coachName,
        room,
        startAt: `${addDays(today, offset)}T${start}:00+07:00`,
        endAt: `${addDays(today, offset)}T${end}:00+07:00`,
        cancellationDeadline: `${addDays(today, offset)}T12:00:00+07:00`,
        confirmedCount,
        capacity,
        status: "Scheduled",
      }),
    ),
    enrollments: [
      {
        sessionId: "yoga",
        memberPackageId: "member-gold",
        status: "Confirmed",
      },
    ],
    packages: [
      {
        id: "member-gold",
        packageId: "gold",
        name: "Gold Member",
        expiresAt: `${addDays(today, 45)}T23:59:59+07:00`,
        status: "Active",
        remainingSessions: 11,
      },
    ],
    catalog: [
      {
        id: "gold",
        name: "Gold Member",
        price: 7500000,
        durationDays: 180,
        sessionLimit: 36,
        benefits: [
          "36 training sessions in 6 months",
          "Gym and Yoga Classs",
          "2 PT 1–1",
        ],
      },
      {
        id: "diamond",
        name: "Diamond All-Access",
        price: 23400000,
        durationDays: 365,
        sessionLimit: null,
        benefits: [
          "12 months without deadlines",
          "Classes at the Center",
          "Training With Coach",
        ],
      },
    ],
    invoices: [],
    coaches: [
      {
        id: "linh",
        name: "Ling Ling",
        specialty: "Yoga & GroupX",
        bio: "Your companion improves flexibility, breathing, and maintains motivation in group classes.",
        initials: "DRL",
      },
      {
        id: "alex",
        name: "Alex Morgan",
        specialty: "& Personal Training Force",
        bio: "Building physical and technical platforms is consistent with personal goals.",
        initials: "AM",
      },
    ],
    notifications: [
      {
        id: "schedule",
        title: "Your School Calendar",
        body: "Yoga basically started at 18:30 at Studio A. Your place has been held.",
        href: "/member/calendar",
        read: false,
        createdAt: new Date().toISOString(),
      },
      {
        id: "training",
        title: "New remarks from the coach",
        body: "Alex Morgan updated after the last training session.",
        href: "/member/training",
        read: false,
        createdAt: new Date().toISOString(),
      },
    ],
    training: {
      goal: "Extensive Power",
      coach: "Alex Morgan",
      exercises: [
        { name: "Squat", sets: 3, reps: "Twelve times" },
        { name: "Plank", sets: 3, reps: "30 sec" },
      ],
      comment:
        "Keep breathing and technical preference before increased intensity.",
    },
    history: [
      {
        id: "h1",
        className: "Basic Body",
        date: addDays(today, -2),
        attendance: "Present",
        result: "Completed 3/3 rounds",
        coachComment: "Control your breathing better.",
      },
      {
        id: "h2",
        className: "Basic Yoga",
        date: addDays(today, -4),
        attendance: "Present",
        result: "Completed training session",
        coachComment: "Improved posture and flexibility.",
      },
      {
        id: "h3",
        className: "Basic Body",
        date: addDays(today, -6),
        attendance: "Absent",
      },
    ],
  };
}
