import type { MemberSnapshot } from "@/application/member/contracts";
import { addDays, dayKey } from "@/shared/lib/date";

export function createSeed(): MemberSnapshot {
  const today = dayKey();
  const sessions = [
    [
      "yoga",
      "Yoga cơ bản",
      "Yoga",
      "linh",
      "Linh Đặng",
      "Studio A",
      1,
      "18:30",
      "19:30",
      16,
      20,
    ],
    [
      "strength",
      "Thể lực cơ bản",
      "Fitness",
      "alex",
      "Alex Morgan",
      "Phòng Gym",
      2,
      "17:00",
      "18:00",
      14,
      20,
    ],
    [
      "groupx",
      "GroupX",
      "GroupX",
      "linh",
      "Linh Đặng",
      "Studio B",
      3,
      "07:00",
      "08:00",
      12,
      12,
    ],
    [
      "stretch",
      "Giãn cơ & phục hồi",
      "Fitness",
      "alex",
      "Alex Morgan",
      "Studio A",
      4,
      "18:00",
      "19:00",
      8,
      16,
    ],
    [
      "yoga-next",
      "Yoga cơ bản",
      "Yoga",
      "linh",
      "Linh Đặng",
      "Studio A",
      8,
      "18:30",
      "19:30",
      10,
      20,
    ],
  ] as const;
  return {
    version: 1,
    profile: {
      id: "demo-member",
      fullName: "Minh Triết",
      email: "minhtriet@example.com",
      phone: "",
      goal: "Tăng sức bền",
      level: "Beginner",
    },
    sessions: sessions.map(
      ([
        id,
        name,
        discipline,
        coachId,
        coachName,
        room,
        offset,
        start,
        end,
        confirmedCount,
        capacity,
      ]) => ({
        id,
        name,
        discipline,
        coachId,
        coachName,
        room,
        startAt: `${addDays(today, offset)}T${start}:00+07:00`,
        endAt: `${addDays(today, offset)}T${end}:00+07:00`,
        cancellationDeadline: `${addDays(today, offset)}T12:00:00+07:00`,
        confirmedCount,
        capacity,
        status: "Scheduled",
      }),
    ),
    enrollments: [
      {
        sessionId: "yoga",
        memberPackageId: "member-gold",
        status: "Confirmed",
      },
    ],
    packages: [
      {
        id: "member-gold",
        packageId: "gold",
        name: "Gold Member",
        expiresAt: `${addDays(today, 45)}T23:59:59+07:00`,
        status: "Active",
        remainingSessions: 11,
      },
    ],
    catalog: [
      {
        id: "gold",
        name: "Gold Member",
        price: 7500000,
        durationDays: 180,
        sessionLimit: 36,
        benefits: [
          "36 buổi tập trong 6 tháng",
          "Các lớp Gym và Yoga",
          "2 buổi PT 1–1",
        ],
      },
      {
        id: "diamond",
        name: "Diamond All-Access",
        price: 23400000,
        durationDays: 365,
        sessionLimit: null,
        benefits: [
          "12 tháng không giới hạn buổi",
          "Các lớp tại trung tâm",
          "Tập luyện cùng huấn luyện viên",
        ],
      },
    ],
    invoices: [],
    coaches: [
      {
        id: "linh",
        name: "Linh Đặng",
        specialty: "Yoga & GroupX",
        bio: "Đồng hành cùng bạn cải thiện độ linh hoạt, nhịp thở và duy trì động lực trong các lớp tập nhóm.",
        initials: "LĐ",
      },
      {
        id: "alex",
        name: "Alex Morgan",
        specialty: "Thể lực & tập luyện cá nhân",
        bio: "Xây dựng nền tảng thể lực và kỹ thuật tập phù hợp với mục tiêu cá nhân.",
        initials: "AM",
      },
    ],
    notifications: [
      {
        id: "schedule",
        title: "Lịch học của bạn",
        body: "Yoga cơ bản bắt đầu lúc 18:30 tại Studio A. Chỗ của bạn đã được giữ.",
        href: "/member/calendar",
        read: false,
        createdAt: new Date().toISOString(),
      },
      {
        id: "training",
        title: "Nhận xét mới từ huấn luyện viên",
        body: "Alex Morgan đã cập nhật nhận xét sau buổi tập gần nhất.",
        href: "/member/training",
        read: false,
        createdAt: new Date().toISOString(),
      },
    ],
    training: {
      goal: "Tăng sức bền",
      coach: "Alex Morgan",
      exercises: [
        { name: "Squat", sets: 3, reps: "12 lần" },
        { name: "Plank", sets: 3, reps: "30 giây" },
      ],
      comment: "Giữ nhịp thở đều và ưu tiên kỹ thuật trước khi tăng cường độ.",
    },
    history: [
      {
        id: "h1",
        className: "Thể lực cơ bản",
        date: addDays(today, -2),
        attendance: "Present",
        result: "Hoàn thành 3/3 hiệp",
        coachComment: "Kiểm soát nhịp thở tốt hơn.",
      },
      {
        id: "h2",
        className: "Yoga cơ bản",
        date: addDays(today, -4),
        attendance: "Present",
        result: "Hoàn thành buổi tập",
        coachComment: "Cải thiện tư thế và độ linh hoạt.",
      },
      {
        id: "h3",
        className: "Thể lực cơ bản",
        date: addDays(today, -6),
        attendance: "Absent",
      },
    ],
  };
}
