"use client";
import { useState } from "react";
import { AsyncSection, Card, Field, StatusChip } from "@/components/ui";
import { api } from "@/lib/apiClient";
import { useApi } from "@/lib/useApi";
import { useLanguage } from "@/lib/language";
import { MutationFeedback, useMutation } from "@/features/operations";
import type { WorkoutPlanDto } from "@/lib/types";
import { ptApi } from "./api";
import { ListPager } from "./ui";
import { PtMemberSelect } from "./member-select";
import { ExerciseEditor, emptyExercise, type ExerciseDraft } from "./exercise-editor";
function PlanEditor({ plan, reload }: { plan?: WorkoutPlanDto; reload: () => void }) { const { t } = useLanguage(); const l = t.staffWork; const mutation = useMutation(); const [member, setMember] = useState(plan?.memberId ?? ""); const [goal, setGoal] = useState(plan?.goal ?? ""); const [level, setLevel] = useState(plan?.level ?? "Beginner"); const [items, setItems] = useState<ExerciseDraft[]>(plan?.items ?? [emptyExercise()]); return <form className="form" onSubmit={async e => { e.preventDefault(); const body = { memberId: member, goal: goal.trim(), level, items: items.map(({ exercise, sets, reps, notes }) => ({ exercise: exercise.trim(), sets, reps, notes })), version: plan?.version }; if (await mutation.run(() => plan ? api.put(`/api/workout-plans/${plan.planId}`, body) : api.post("/api/workout-plans", body))) reload(); }}>{plan ? <p>{plan.memberName}</p> : <PtMemberSelect value={member} onChange={setMember}/>}<Field label={l.goal}><input required minLength={3} maxLength={500} value={goal} onChange={e => setGoal(e.target.value)}/></Field><Field label={l.level}><input required maxLength={50} value={level} onChange={e => setLevel(e.target.value)}/></Field><ExerciseEditor items={items} onChange={setItems}/><MutationFeedback mutation={mutation}/><button className="btn" disabled={mutation.busy || !member}>{l.save}</button></form>; }
function PlanCard({ plan: p, reload }: { plan: WorkoutPlanDto; reload: () => void }) { const { t } = useLanguage(); const l = t.staffWork; const [editing, setEditing] = useState(false); const mutation = useMutation(); async function transition(action: string) { if (await mutation.run(() => api.post(`/api/workout-plans/${p.planId}/${action}`))) reload(); } return <Card title={`${p.memberName} · ${p.goal}`}><p><StatusChip value={p.status}/> · {p.level}</p><ul>{p.items.map(i => <li key={i.itemId}>{i.exercise} · {i.sets} × {i.reps} · {i.notes}</li>)}</ul><div className="btn-row"><button className="btn btn--secondary" onClick={() => setEditing(!editing)}>{l.edit}</button><button className="btn btn--secondary" disabled={mutation.busy || p.status === "ACTIVE"} onClick={() => transition("activate")}>{l.activate}</button><button className="btn btn--secondary" disabled={mutation.busy || p.status === "ARCHIVED"} onClick={() => transition("archive")}>{l.archive}</button></div><MutationFeedback mutation={mutation}/>{editing && <PlanEditor plan={p} reload={reload}/>}</Card>; }
export function TrainingPlans() { const { t } = useLanguage(); const [page, setPage] = useState(1); const [revision, setRevision] = useState(0); const state = useApi(signal => ptApi.plans(page, signal), [page, revision]); const reload = () => setRevision(r => r + 1); return <><Card title={t.staffWork.newPlan}><PlanEditor key={revision} reload={reload}/></Card><AsyncSection state={state}>{rows => <>{rows.map(p => <PlanCard key={`${p.planId}-${p.version}`} plan={p} reload={reload}/>)}{!rows.length && <p>{t.common.noData}</p>}<ListPager page={page} count={rows.length} onChange={setPage}/></>}</AsyncSection></>; }
