CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE membership_packages (
    package_id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    price numeric(18,0) NOT NULL,
    duration_days integer NOT NULL,
    session_limit integer,
    CONSTRAINT pk_membership_packages PRIMARY KEY (package_id)
);

CREATE TABLE roles (
    role_id integer GENERATED BY DEFAULT AS IDENTITY,
    role_name integer NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE rooms (
    room_id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    capacity integer NOT NULL,
    CONSTRAINT pk_rooms PRIMARY KEY (room_id)
);

CREATE TABLE user_accounts (
    user_id uuid NOT NULL,
    email citext NOT NULL,
    role_id integer NOT NULL,
    status integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_accounts PRIMARY KEY (user_id),
    CONSTRAINT fk_user_accounts_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE RESTRICT
);

CREATE TABLE ai_logs (
    log_id uuid NOT NULL,
    user_id uuid NOT NULL,
    query_type text NOT NULL,
    input_payload jsonb NOT NULL,
    response_payload jsonb NOT NULL,
    response_time_ms integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_ai_logs PRIMARY KEY (log_id),
    CONSTRAINT fk_ai_logs_user_accounts_user_id FOREIGN KEY (user_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE audit_logs (
    audit_id uuid NOT NULL,
    user_id uuid NOT NULL,
    action text NOT NULL,
    target_entity text NOT NULL,
    target_id uuid NOT NULL,
    old_value jsonb,
    new_value jsonb,
    ip_address text NOT NULL,
    timestamp timestamp with time zone NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_id),
    CONSTRAINT fk_audit_logs_user_accounts_user_id FOREIGN KEY (user_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE classes (
    class_id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    discipline text NOT NULL,
    default_room_id integer NOT NULL,
    default_coach_id uuid,
    capacity integer NOT NULL,
    status integer NOT NULL,
    CONSTRAINT pk_classes PRIMARY KEY (class_id),
    CONSTRAINT fk_classes_rooms_default_room_id FOREIGN KEY (default_room_id) REFERENCES rooms (room_id) ON DELETE RESTRICT,
    CONSTRAINT fk_classes_user_accounts_default_coach_id FOREIGN KEY (default_coach_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE member_packages (
    member_package_id uuid NOT NULL,
    member_id uuid NOT NULL,
    package_id integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    remaining_sessions integer,
    status integer NOT NULL,
    version integer NOT NULL,
    CONSTRAINT pk_member_packages PRIMARY KEY (member_package_id),
    CONSTRAINT "CK_member_packages_remaining_sessions_non_negative" CHECK (remaining_sessions IS NULL OR remaining_sessions >= 0),
    CONSTRAINT fk_member_packages_membership_packages_package_id FOREIGN KEY (package_id) REFERENCES membership_packages (package_id) ON DELETE RESTRICT,
    CONSTRAINT fk_member_packages_user_accounts_member_id FOREIGN KEY (member_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE member_training_profiles (
    profile_id uuid NOT NULL,
    member_id uuid NOT NULL,
    goal text NOT NULL,
    experience_level integer NOT NULL,
    notes text,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_member_training_profiles PRIMARY KEY (profile_id),
    CONSTRAINT fk_member_training_profiles_user_accounts_member_id FOREIGN KEY (member_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE notifications (
    notification_id uuid NOT NULL,
    user_id uuid NOT NULL,
    channel integer NOT NULL,
    source_event_type integer NOT NULL,
    source_entity_id uuid,
    message text NOT NULL,
    status integer NOT NULL,
    retry_count integer NOT NULL,
    last_attempt_at timestamp with time zone,
    sent_at timestamp with time zone,
    CONSTRAINT pk_notifications PRIMARY KEY (notification_id),
    CONSTRAINT fk_notifications_user_accounts_user_id FOREIGN KEY (user_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE user_credentials (
    user_id uuid NOT NULL,
    password_hash text,
    CONSTRAINT pk_user_credentials PRIMARY KEY (user_id),
    CONSTRAINT fk_user_credentials_user_accounts_user_id FOREIGN KEY (user_id) REFERENCES user_accounts (user_id) ON DELETE CASCADE
);

CREATE TABLE user_external_logins (
    external_login_id uuid NOT NULL,
    user_id uuid NOT NULL,
    provider integer NOT NULL,
    provider_user_id text NOT NULL,
    refresh_token text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_user_external_logins PRIMARY KEY (external_login_id),
    CONSTRAINT fk_user_external_logins_user_accounts_user_id FOREIGN KEY (user_id) REFERENCES user_accounts (user_id) ON DELETE CASCADE
);

CREATE TABLE user_profiles (
    user_id uuid NOT NULL,
    full_name text NOT NULL,
    phone text,
    CONSTRAINT pk_user_profiles PRIMARY KEY (user_id),
    CONSTRAINT fk_user_profiles_user_accounts_user_id FOREIGN KEY (user_id) REFERENCES user_accounts (user_id) ON DELETE CASCADE
);

CREATE TABLE class_recurrences (
    recurrence_id integer GENERATED BY DEFAULT AS IDENTITY,
    class_id integer NOT NULL,
    days_of_week text NOT NULL,
    start_time_local time without time zone NOT NULL,
    end_time_local time without time zone NOT NULL,
    timezone text NOT NULL,
    effective_from date NOT NULL,
    effective_to date,
    CONSTRAINT pk_class_recurrences PRIMARY KEY (recurrence_id),
    CONSTRAINT fk_class_recurrences_classes_class_id FOREIGN KEY (class_id) REFERENCES classes (class_id) ON DELETE RESTRICT
);

CREATE TABLE coach_member_relationships (
    relationship_id uuid NOT NULL,
    coach_id uuid NOT NULL,
    member_id uuid NOT NULL,
    source_type integer NOT NULL,
    class_id integer,
    status integer NOT NULL,
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    CONSTRAINT pk_coach_member_relationships PRIMARY KEY (relationship_id),
    CONSTRAINT fk_coach_member_relationships_classes_class_id FOREIGN KEY (class_id) REFERENCES classes (class_id) ON DELETE RESTRICT,
    CONSTRAINT fk_coach_member_relationships_user_accounts_coach_id FOREIGN KEY (coach_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_coach_member_relationships_user_accounts_member_id FOREIGN KEY (member_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE invoices (
    invoice_id uuid NOT NULL,
    invoice_number text NOT NULL,
    member_id uuid NOT NULL,
    issued_by_user_id uuid NOT NULL,
    member_package_id uuid,
    total_amount numeric(18,0) NOT NULL,
    status integer NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (invoice_id),
    CONSTRAINT fk_invoices_member_packages_member_package_id FOREIGN KEY (member_package_id) REFERENCES member_packages (member_package_id) ON DELETE RESTRICT,
    CONSTRAINT fk_invoices_user_accounts_issued_by_user_id FOREIGN KEY (issued_by_user_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_invoices_user_accounts_member_id FOREIGN KEY (member_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE class_sessions (
    session_id uuid NOT NULL,
    class_id integer NOT NULL,
    recurrence_id integer,
    room_id integer NOT NULL,
    coach_id uuid NOT NULL,
    start_at_utc timestamp with time zone NOT NULL,
    end_at_utc timestamp with time zone NOT NULL,
    capacity integer NOT NULL,
    confirmed_count integer NOT NULL,
    status integer NOT NULL,
    rescheduled_from_session_id uuid,
    CONSTRAINT pk_class_sessions PRIMARY KEY (session_id),
    CONSTRAINT "CK_class_sessions_confirmed_count_within_capacity" CHECK (confirmed_count >= 0 AND confirmed_count <= capacity),
    CONSTRAINT fk_class_sessions_class_recurrences_recurrence_id FOREIGN KEY (recurrence_id) REFERENCES class_recurrences (recurrence_id) ON DELETE RESTRICT,
    CONSTRAINT fk_class_sessions_class_sessions_rescheduled_from_session_id FOREIGN KEY (rescheduled_from_session_id) REFERENCES class_sessions (session_id) ON DELETE RESTRICT,
    CONSTRAINT fk_class_sessions_classes_class_id FOREIGN KEY (class_id) REFERENCES classes (class_id) ON DELETE RESTRICT,
    CONSTRAINT fk_class_sessions_rooms_room_id FOREIGN KEY (room_id) REFERENCES rooms (room_id) ON DELETE RESTRICT,
    CONSTRAINT fk_class_sessions_user_accounts_coach_id FOREIGN KEY (coach_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE workout_plans (
    plan_id uuid NOT NULL,
    member_id uuid NOT NULL,
    coach_id uuid NOT NULL,
    relationship_id uuid NOT NULL,
    goal text NOT NULL,
    level text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_workout_plans PRIMARY KEY (plan_id),
    CONSTRAINT fk_workout_plans_coach_member_relationships_relationship_id FOREIGN KEY (relationship_id) REFERENCES coach_member_relationships (relationship_id) ON DELETE RESTRICT,
    CONSTRAINT fk_workout_plans_user_accounts_coach_id FOREIGN KEY (coach_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_workout_plans_user_accounts_member_id FOREIGN KEY (member_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE invoice_items (
    item_id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    description text NOT NULL,
    amount numeric(18,0) NOT NULL,
    related_entity_type integer NOT NULL,
    related_entity_id uuid,
    CONSTRAINT pk_invoice_items PRIMARY KEY (item_id),
    CONSTRAINT fk_invoice_items_invoices_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices (invoice_id) ON DELETE CASCADE
);

CREATE TABLE payments (
    payment_id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    amount numeric(18,0) NOT NULL,
    method integer NOT NULL,
    reference_code text,
    status integer NOT NULL,
    received_by_user_id uuid NOT NULL,
    paid_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (payment_id),
    CONSTRAINT fk_payments_invoices_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices (invoice_id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_user_accounts_received_by_user_id FOREIGN KEY (received_by_user_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE enrollments (
    enrollment_id uuid NOT NULL,
    session_id uuid NOT NULL,
    member_id uuid NOT NULL,
    member_package_id uuid NOT NULL,
    status integer NOT NULL,
    registered_at timestamp with time zone NOT NULL,
    cancelled_at timestamp with time zone,
    cancelled_by_user_id uuid,
    CONSTRAINT pk_enrollments PRIMARY KEY (enrollment_id),
    CONSTRAINT fk_enrollments_class_sessions_session_id FOREIGN KEY (session_id) REFERENCES class_sessions (session_id) ON DELETE RESTRICT,
    CONSTRAINT fk_enrollments_member_packages_member_package_id FOREIGN KEY (member_package_id) REFERENCES member_packages (member_package_id) ON DELETE RESTRICT,
    CONSTRAINT fk_enrollments_user_accounts_cancelled_by_user_id FOREIGN KEY (cancelled_by_user_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_enrollments_user_accounts_member_id FOREIGN KEY (member_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE workout_plan_items (
    item_id uuid NOT NULL,
    plan_id uuid NOT NULL,
    exercise text NOT NULL,
    sets integer NOT NULL,
    reps integer NOT NULL,
    notes text,
    CONSTRAINT pk_workout_plan_items PRIMARY KEY (item_id),
    CONSTRAINT fk_workout_plan_items_workout_plans_plan_id FOREIGN KEY (plan_id) REFERENCES workout_plans (plan_id) ON DELETE CASCADE
);

CREATE TABLE payment_adjustments (
    adjustment_id uuid NOT NULL,
    invoice_id uuid NOT NULL,
    payment_id uuid,
    type integer NOT NULL,
    amount numeric(18,0) NOT NULL,
    reason text NOT NULL,
    status integer NOT NULL,
    requested_by_user_id uuid NOT NULL,
    approved_by_user_id uuid,
    created_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    CONSTRAINT pk_payment_adjustments PRIMARY KEY (adjustment_id),
    CONSTRAINT fk_payment_adjustments_invoices_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices (invoice_id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_adjustments_payments_payment_id FOREIGN KEY (payment_id) REFERENCES payments (payment_id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_adjustments_user_accounts_approved_by_user_id FOREIGN KEY (approved_by_user_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_adjustments_user_accounts_requested_by_user_id FOREIGN KEY (requested_by_user_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE attendances (
    attendance_id uuid NOT NULL,
    enrollment_id uuid NOT NULL,
    status integer NOT NULL,
    check_in_time timestamp with time zone,
    checked_in_by_user_id uuid,
    CONSTRAINT pk_attendances PRIMARY KEY (attendance_id),
    CONSTRAINT fk_attendances_enrollments_enrollment_id FOREIGN KEY (enrollment_id) REFERENCES enrollments (enrollment_id) ON DELETE RESTRICT,
    CONSTRAINT fk_attendances_user_accounts_checked_in_by_user_id FOREIGN KEY (checked_in_by_user_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

CREATE TABLE workout_results (
    result_id uuid NOT NULL,
    enrollment_id uuid NOT NULL,
    coach_id uuid NOT NULL,
    progress_note text,
    coach_comment text,
    recorded_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_workout_results PRIMARY KEY (result_id),
    CONSTRAINT fk_workout_results_enrollments_enrollment_id FOREIGN KEY (enrollment_id) REFERENCES enrollments (enrollment_id) ON DELETE RESTRICT,
    CONSTRAINT fk_workout_results_user_accounts_coach_id FOREIGN KEY (coach_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
);

INSERT INTO roles (role_id, role_name)
VALUES (1, 0);
INSERT INTO roles (role_id, role_name)
VALUES (2, 1);
INSERT INTO roles (role_id, role_name)
VALUES (3, 2);
INSERT INTO roles (role_id, role_name)
VALUES (4, 3);
INSERT INTO roles (role_id, role_name)
VALUES (5, 4);

CREATE INDEX ix_ai_logs_user_id ON ai_logs (user_id);

CREATE INDEX ix_attendances_checked_in_by_user_id ON attendances (checked_in_by_user_id);

CREATE UNIQUE INDEX ix_attendances_enrollment_id ON attendances (enrollment_id);

CREATE INDEX ix_audit_logs_user_id ON audit_logs (user_id);

CREATE INDEX ix_class_recurrences_class_id ON class_recurrences (class_id);

CREATE INDEX ix_class_sessions_class_id ON class_sessions (class_id);

CREATE INDEX ix_class_sessions_coach_id ON class_sessions (coach_id);

CREATE INDEX ix_class_sessions_recurrence_id ON class_sessions (recurrence_id);

CREATE INDEX ix_class_sessions_rescheduled_from_session_id ON class_sessions (rescheduled_from_session_id);

CREATE INDEX ix_class_sessions_room_id ON class_sessions (room_id);

CREATE INDEX ix_classes_default_coach_id ON classes (default_coach_id);

CREATE INDEX ix_classes_default_room_id ON classes (default_room_id);

CREATE INDEX ix_coach_member_relationships_class_id ON coach_member_relationships (class_id);

CREATE UNIQUE INDEX ix_coach_member_relationships_coach_id_member_id ON coach_member_relationships (coach_id, member_id) WHERE status = 0;

CREATE INDEX ix_coach_member_relationships_member_id ON coach_member_relationships (member_id);

CREATE INDEX ix_enrollments_cancelled_by_user_id ON enrollments (cancelled_by_user_id);

CREATE INDEX ix_enrollments_member_id ON enrollments (member_id);

CREATE INDEX ix_enrollments_member_package_id ON enrollments (member_package_id);

CREATE UNIQUE INDEX ix_enrollments_session_id_member_id ON enrollments (session_id, member_id) WHERE status = 0;

CREATE INDEX ix_invoice_items_invoice_id ON invoice_items (invoice_id);

CREATE UNIQUE INDEX ix_invoices_invoice_number ON invoices (invoice_number);

CREATE INDEX ix_invoices_issued_by_user_id ON invoices (issued_by_user_id);

CREATE INDEX ix_invoices_member_id ON invoices (member_id);

CREATE INDEX ix_invoices_member_package_id ON invoices (member_package_id);

CREATE INDEX ix_member_packages_member_id ON member_packages (member_id);

CREATE INDEX ix_member_packages_package_id ON member_packages (package_id);

CREATE UNIQUE INDEX ix_member_training_profiles_member_id ON member_training_profiles (member_id);

CREATE UNIQUE INDEX ix_membership_packages_name ON membership_packages (name);

CREATE INDEX ix_notifications_user_id ON notifications (user_id);

CREATE INDEX ix_payment_adjustments_approved_by_user_id ON payment_adjustments (approved_by_user_id);

CREATE INDEX ix_payment_adjustments_invoice_id ON payment_adjustments (invoice_id);

CREATE INDEX ix_payment_adjustments_payment_id ON payment_adjustments (payment_id);

CREATE INDEX ix_payment_adjustments_requested_by_user_id ON payment_adjustments (requested_by_user_id);

CREATE INDEX ix_payments_invoice_id ON payments (invoice_id);

CREATE INDEX ix_payments_received_by_user_id ON payments (received_by_user_id);

CREATE UNIQUE INDEX ix_roles_role_name ON roles (role_name);

CREATE UNIQUE INDEX ix_rooms_name ON rooms (name);

CREATE UNIQUE INDEX ix_user_accounts_email ON user_accounts (email);

CREATE INDEX ix_user_accounts_role_id ON user_accounts (role_id);

CREATE UNIQUE INDEX ix_user_external_logins_provider_provider_user_id ON user_external_logins (provider, provider_user_id);

CREATE UNIQUE INDEX ix_user_external_logins_user_id_provider ON user_external_logins (user_id, provider);

CREATE UNIQUE INDEX ix_user_profiles_phone ON user_profiles (phone) WHERE phone IS NOT NULL;

CREATE INDEX ix_workout_plan_items_plan_id ON workout_plan_items (plan_id);

CREATE INDEX ix_workout_plans_coach_id ON workout_plans (coach_id);

CREATE INDEX ix_workout_plans_member_id ON workout_plans (member_id);

CREATE INDEX ix_workout_plans_relationship_id ON workout_plans (relationship_id);

CREATE INDEX ix_workout_results_coach_id ON workout_results (coach_id);

CREATE INDEX ix_workout_results_enrollment_id ON workout_results (enrollment_id);

SELECT setval(
    pg_get_serial_sequence('roles', 'role_id'),
    GREATEST(
        (SELECT MAX(role_id) FROM roles) + 1,
        nextval(pg_get_serial_sequence('roles', 'role_id'))),
    false);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260912123957_InitialCreate', '10.0.11');

COMMIT;

