"use client";
import { useState } from "react";
import { AsyncSection, Card, Field, Pager, StatusChip, Table } from "@/components/ui";
import { api } from "@/lib/apiClient";
import { useApi } from "@/lib/useApi";
import { useAuth } from "@/lib/auth";
import { useLanguage } from "@/lib/language";
import { MutationFeedback, useMutation } from "@/features/operations";
import { PasswordRequirements, passwordChecks } from "@/features/identity";
import type { SportDto, Paged, UserAdminDto } from "@/lib/types";
const staffRoles = ["CENTER_MANAGER", "COACH", "RECEPTIONIST", "SYSTEM_ADMINISTRATOR"];
function RoleSelect({ value, onChange, member = false }: { value: string; onChange: (value: string) => void; member?: boolean }) { const { t } = useLanguage(); return <Field label={t.staffWork.role}><select value={value} onChange={e => onChange(e.target.value)}>{[...staffRoles, ...(member ? ["MEMBER"] : [])].map(r => <option key={r} value={r}>{t.wireStatus[r as keyof typeof t.wireStatus] ?? r}</option>)}</select></Field>; }
function SportSelect({ value, onChange }: { value: number[]; onChange: (value: number[]) => void }) { const { t } = useLanguage(); const state = useApi(signal => api.get<SportDto[]>("/api/sports", { signal }), []); return <AsyncSection state={state}>{rows => <fieldset><legend>{t.staffWork.specialties}</legend>{rows.filter(s => s.isActive).map(s => <label key={s.sportId}><input type="checkbox" checked={value.includes(s.sportId)} onChange={e => onChange(e.target.checked ? [...value, s.sportId] : value.filter(id => id !== s.sportId))}/>{s.name}</label>)}</fieldset>}</AsyncSection>; }
function CreateStaff({ reload }: { reload: () => void }) { const { t } = useLanguage(); const l = t.staffWork; const mutation = useMutation(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [role, setRole] = useState("RECEPTIONIST"); const [sports, setSports] = useState<number[]>([]);
 return <Card title={l.staffCreate}><form className="form" onSubmit={async e => { e.preventDefault(); if (await mutation.run(() => api.post("/api/users", { email: email.trim(), password, fullName: name.trim(), phone: phone.trim() || null, role, sportIds: role === "COACH" ? sports : [] }))) { setPassword(""); setConfirm(""); reload(); } }}><div className="form-grid"><Field label={l.email}><input type="email" required value={email} onChange={e => setEmail(e.target.value)}/></Field><Field label={l.fullName}><input required value={name} onChange={e => setName(e.target.value)}/></Field><Field label={l.phone}><input type="tel" value={phone} onChange={e => setPhone(e.target.value)}/></Field><Field label={l.password}><input type="password" required autoComplete="new-password" maxLength={64} value={password} onChange={e => setPassword(e.target.value)}/></Field><Field label={l.confirmPassword}><input type="password" required autoComplete="new-password" maxLength={64} value={confirm} onChange={e => setConfirm(e.target.value)}/></Field></div><PasswordRequirements email={email} password={password}/>{confirm && confirm !== password && <p role="alert">{l.mismatch}</p>}<RoleSelect value={role} onChange={r => { setRole(r); setSports([]); }}/>{role === "COACH" && <SportSelect value={sports} onChange={setSports}/>}<MutationFeedback mutation={mutation}/><button className="btn" disabled={mutation.busy || !passwordChecks(password, email).every(Boolean) || password !== confirm || (role === "COACH" && !sports.length)}>{l.staffCreate}</button></form></Card>;
}
function EditUser({ account: a, reload }: { account: UserAdminDto; reload: () => void }) { const { t } = useLanguage(); const l = t.staffWork; const { user, logout } = useAuth(); const [role, setRole] = useState(a.role); const [sports, setSports] = useState(a.sportIds); const [reason, setReason] = useState(""); const mutation = useMutation(); async function action(name: string) { const ok = await mutation.run(() => name === "role" ? api.put(`/api/users/${a.userId}/role`, { role, reason: reason.trim(), sportIds: role === "COACH" ? sports : [] }) : api.post(`/api/users/${a.userId}/${name}`, { reason: reason.trim() })); if (ok) { if (name === "role" && a.userId === user?.userId) logout(); reload(); } }
 return <Card title={`${a.fullName} · ${a.email}`}><Field label={l.reason}><textarea required minLength={3} maxLength={500} value={reason} onChange={e => setReason(e.target.value)}/></Field>{a.role !== "EXTERNAL_COACH" && <><RoleSelect member value={role} onChange={r => { setRole(r); setSports([]); }}/>{role === "COACH" && <SportSelect value={sports} onChange={setSports}/>}<button className="btn" disabled={mutation.busy || reason.trim().length < 3 || (role === "COACH" && !sports.length) || role === a.role} onClick={() => action("role")}>{l.changeRole}</button></>}<div className="btn-row">{a.userId !== user?.userId && <>{a.status !== "BANNED" && <button className="btn btn--danger" disabled={mutation.busy || reason.trim().length < 3} onClick={() => action("lock")}>{l.lock}</button>}{a.status !== "ACTIVE" && <button className="btn btn--secondary" disabled={mutation.busy || reason.trim().length < 3} onClick={() => action("unlock")}>{l.unlock}</button>}{a.status !== "DEACTIVATED" && <button className="btn btn--secondary" disabled={mutation.busy || reason.trim().length < 3} onClick={() => action("deactivate")}>{l.deactivate}</button>}</>}</div><MutationFeedback mutation={mutation}/></Card>;
}
export function Users() { const { t } = useLanguage(); const l = t.staffWork; const [page, setPage] = useState(1); const [keyword, setKeyword] = useState(""); const [selected, setSelected] = useState<UserAdminDto | null>(null); const [create, setCreate] = useState(false); const state = useApi(signal => api.get<Paged<UserAdminDto>>("/api/users/admin", { signal, query: { page, pageSize: 20, keyword } }), [page, keyword]); const reload = () => { setSelected(null); state.reload(); }; return <><Card title={l.users}><Field label={l.keyword}><input value={keyword} onChange={e => { setKeyword(e.target.value); setPage(1); setSelected(null); }}/></Field><button className="btn" onClick={() => setCreate(!create)}>{l.staffCreate}</button><AsyncSection state={state}>{data => <><Table headers={[l.fullName, l.email, l.role, l.status, l.actions]}>{data.items.map(a => <tr key={a.userId}><td>{a.fullName}</td><td>{a.email}</td><td><StatusChip value={a.role}/></td><td><StatusChip value={a.status}/></td><td><button className="btn btn--secondary" onClick={() => setSelected(a)}>{l.edit}</button></td></tr>)}</Table><Pager page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} onChange={setPage}/></>}</AsyncSection></Card>{create && <CreateStaff reload={reload}/>} {selected && <EditUser key={selected.userId} account={selected} reload={reload}/>}</>; }
