"use client";
import { useState } from "react";
import { AsyncSection, Card, Field, Pager, StatusChip } from "@/components/ui";
import { api } from "@/lib/apiClient";
import { useApi } from "@/lib/useApi";
import { useAuth } from "@/lib/auth";
import { useLanguage } from "@/lib/language";
import { formatPoints, formatMoney } from "@/lib/format";
import type { PaymentAdjustmentDto, Paged } from "@/lib/types";
import { MutationFeedback, useMutation } from "@/features/operations";
function RefundCard({ r, reload }: { r: PaymentAdjustmentDto; reload: () => void }) { const { t } = useLanguage(); const l = t.staffWork; const { user } = useAuth(); const [reason, setReason] = useState(""); const [centerFault, setCenterFault] = useState(false); const mutation = useMutation(); const legacy = !r.invoiceItemId; const canReview = !legacy && r.status === "REQUESTED" && r.requestedByUserId !== user?.userId;
 async function review(approve: boolean) { if (await mutation.run(() => api.post(`/api/refunds/${r.adjustmentId}/${approve ? "approve" : "reject"}`, { reason: reason.trim(), ...(approve ? { centerFault } : {}) }))) reload(); }
 return <Card title={r.invoiceNumber} hint={legacy ? l.legacy : l.refundHint}><p><StatusChip value={r.status}/></p><p>{r.reason}</p>{legacy ? <p>{formatMoney(r.amount)}</p> : <><p>{l.invoiceItem}: {r.invoiceItemId}</p><p>{l.systemCap}: {formatPoints(r.systemCalculatedPoints)} · {l.approvedPoints}: {formatPoints(r.approvedPoints ?? 0)}</p>{r.pointLedgerEntryId && <p>{l.ledger}: {r.pointLedgerEntryId}</p>}</>}{r.status === "REQUESTED" && !legacy && !canReview && <p>{l.refundSelf}</p>}{canReview && <><Field label={l.reviewNote}><textarea required minLength={3} maxLength={500} value={reason} onChange={e => setReason(e.target.value)}/></Field><label><input type="checkbox" checked={centerFault} onChange={e => setCenterFault(e.target.checked)}/>{l.centerFault}</label><div className="btn-row"><button className="btn" disabled={mutation.busy || reason.trim().length < 3} onClick={() => review(true)}>{l.approve}</button><button className="btn btn--danger" disabled={mutation.busy || reason.trim().length < 3} onClick={() => review(false)}>{l.reject}</button></div></>}<MutationFeedback mutation={mutation}/></Card>;
}
export function ManagerRefunds() { const { t } = useLanguage(); const l = t.staffWork; const [page, setPage] = useState(1); const [status, setStatus] = useState(""); const [legacy, setLegacy] = useState(false); const state = useApi(signal => api.get<Paged<PaymentAdjustmentDto>>(legacy ? "/api/payment-adjustments" : "/api/refunds", { signal, query: { page, pageSize: 20, status } }), [page, status, legacy]); return <><Card><Field label={l.status}><select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">{l.all}</option>{["REQUESTED", "COMPLETED", "REJECTED"].map(s => <option key={s} value={s}>{t.wireStatus[s as keyof typeof t.wireStatus] ?? s}</option>)}</select></Field><label><input type="checkbox" checked={legacy} onChange={e => { setLegacy(e.target.checked); setPage(1); }}/>{l.legacy}</label><button className="btn btn--secondary" onClick={state.reload}>{l.refresh}</button></Card><AsyncSection state={state}>{data => <>{data.items.map(r => legacy ? <Card key={r.adjustmentId} title={r.invoiceNumber} hint={l.legacy}><StatusChip value={r.status}/><p>{r.reason}</p><p>{formatMoney(r.amount)}</p></Card> : <RefundCard key={`${r.adjustmentId}-${r.status}`} r={r} reload={state.reload}/>)}{!data.items.length && <p>{t.common.noData}</p>}<Pager page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} onChange={setPage}/></>}</AsyncSection></>; }
