<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>sporthub-api-secrets</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SportHub.BuildingBlocks\SportHub.BuildingBlocks.csproj" />
    <ProjectReference Include="..\SportHub.Identity\SportHub.Identity.csproj" />
    <ProjectReference Include="..\SportHub.Membership\SportHub.Membership.csproj" />
    <ProjectReference Include="..\SportHub.Scheduling\SportHub.Scheduling.csproj" />
    <ProjectReference Include="..\SportHub.Training\SportHub.Training.csproj" />
    <ProjectReference Include="..\SportHub.Payment\SportHub.Payment.csproj" />
    <ProjectReference Include="..\SportHub.Notification\SportHub.Notification.csproj" />
    <ProjectReference Include="..\SportHub.AI\SportHub.AI.csproj" />
    <ProjectReference Include="..\SportHub.Audit\SportHub.Audit.csproj" />
    <ProjectReference Include="..\SportHub.Administration\SportHub.Administration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

</Project>
