using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SportHub.API.Migrations
{
    /// <summary>
    /// Mô hình lớp theo khóa (P1.05). KHÔNG xóa dữ liệu lớp cũ: các bảng classes, class_recurrences, class_sessions, enrollments,
    /// attendances được ĐỔI TÊN thành legacy_* (kèm chỉ mục, PK và sequence) để giữ nguyên dữ liệu demo/lịch sử, rồi tạo mô hình mới
    /// (classes, class_schedule_rules, class_sessions, seat_holds, enrollments, attendances). Ứng dụng không đọc bảng legacy_*.
    /// Liên kết quan hệ huấn luyện ClassBased → lớp cũ được lưu ở legacy_relationship_class_links rồi gỡ khỏi cột class_id.
    /// Down đưa mọi thứ về như cũ (bảng mới bị xóa cùng dữ liệu mới của chúng).
    /// </summary>
    public partial class MultiSportCourse : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE legacy_relationship_class_links AS
                    SELECT relationship_id, class_id AS legacy_class_id
                    FROM coach_member_relationships
                    WHERE class_id IS NOT NULL;

                ALTER TABLE coach_member_relationships DROP CONSTRAINT fk_coach_member_relationships_classes_class_id;
                UPDATE coach_member_relationships SET class_id = NULL WHERE class_id IS NOT NULL;

                DO $$
                DECLARE r record;
                BEGIN
                    -- Chỉ mục (kể cả PK/unique) của bảng cũ: đổi tên trước để bảng mới dùng lại tên gốc.
                    FOR r IN
                        SELECT indexname FROM pg_indexes
                        WHERE schemaname = current_schema()
                          AND tablename IN ('classes', 'class_recurrences', 'class_sessions', 'enrollments', 'attendances')
                    LOOP
                        EXECUTE format('ALTER INDEX %I RENAME TO %I', r.indexname, 'legacy_' || r.indexname);
                    END LOOP;

                    -- Sequence của cột identity thuộc bảng cũ.
                    FOR r IN
                        SELECT s.relname AS seq
                        FROM pg_class s
                        JOIN pg_depend d ON d.objid = s.oid AND d.deptype IN ('a', 'i')
                        JOIN pg_class t ON t.oid = d.refobjid
                        WHERE s.relkind = 'S'
                          AND t.relname IN ('classes', 'class_recurrences', 'class_sessions', 'enrollments', 'attendances')
                    LOOP
                        EXECUTE format('ALTER SEQUENCE %I RENAME TO %I', r.seq, 'legacy_' || r.seq);
                    END LOOP;
                END $$;

                ALTER TABLE attendances RENAME TO legacy_attendances;
                ALTER TABLE enrollments RENAME TO legacy_enrollments;
                ALTER TABLE class_sessions RENAME TO legacy_class_sessions;
                ALTER TABLE class_recurrences RENAME TO legacy_class_recurrences;
                ALTER TABLE classes RENAME TO legacy_classes;
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE classes (
                    class_id integer GENERATED BY DEFAULT AS IDENTITY,
                    code text NOT NULL,
                    name text NOT NULL,
                    sport_id integer NOT NULL,
                    coach_id uuid,
                    default_room_id integer NOT NULL,
                    start_date date NOT NULL,
                    num_sessions integer NOT NULL,
                    capacity integer NOT NULL,
                    price numeric(18,0) NOT NULL,
                    cost_amount numeric(18,0) NOT NULL,
                    break_even_threshold integer,
                    threshold_status integer NOT NULL,
                    threshold_deadline_utc timestamp with time zone,
                    threshold_response_deadline_utc timestamp with time zone,
                    status integer NOT NULL,
                    confirmed_count integer NOT NULL,
                    reserved_count integer NOT NULL,
                    created_by_ai boolean NOT NULL,
                    version integer NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    published_at timestamp with time zone,
                    CONSTRAINT pk_classes PRIMARY KEY (class_id),
                    CONSTRAINT ck_classes_capacity CHECK (capacity > 0),
                    CONSTRAINT ck_classes_cost CHECK (cost_amount >= 0),
                    CONSTRAINT ck_classes_counts CHECK (confirmed_count >= 0 AND confirmed_count <= reserved_count AND reserved_count <= capacity),
                    CONSTRAINT ck_classes_num_sessions CHECK (num_sessions > 0),
                    CONSTRAINT ck_classes_price CHECK (price > 0 AND price % 1000 = 0),
                    CONSTRAINT fk_classes_rooms_default_room_id FOREIGN KEY (default_room_id) REFERENCES rooms (room_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_classes_sports_sport_id FOREIGN KEY (sport_id) REFERENCES sports (sport_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_classes_user_accounts_coach_id FOREIGN KEY (coach_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
                );

                CREATE TABLE class_schedule_rules (
                    rule_id integer GENERATED BY DEFAULT AS IDENTITY,
                    class_id integer NOT NULL,
                    day_of_week integer NOT NULL,
                    start_time_local time without time zone NOT NULL,
                    CONSTRAINT pk_class_schedule_rules PRIMARY KEY (rule_id),
                    CONSTRAINT ck_class_schedule_rules_day CHECK (day_of_week BETWEEN 0 AND 6),
                    CONSTRAINT fk_class_schedule_rules_classes_class_id FOREIGN KEY (class_id) REFERENCES classes (class_id) ON DELETE CASCADE
                );

                CREATE TABLE class_sessions (
                    session_id uuid NOT NULL,
                    class_id integer NOT NULL,
                    session_no integer NOT NULL,
                    room_id integer NOT NULL,
                    coach_id uuid NOT NULL,
                    start_at_utc timestamp with time zone NOT NULL,
                    end_at_utc timestamp with time zone NOT NULL,
                    status integer NOT NULL,
                    rescheduled_from_session_id uuid,
                    is_makeup boolean NOT NULL,
                    CONSTRAINT pk_class_sessions PRIMARY KEY (session_id),
                    CONSTRAINT ck_class_sessions_no CHECK (session_no > 0),
                    CONSTRAINT ck_class_sessions_range CHECK (end_at_utc > start_at_utc),
                    CONSTRAINT fk_class_sessions_class_sessions_rescheduled_from_session_id FOREIGN KEY (rescheduled_from_session_id) REFERENCES class_sessions (session_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_class_sessions_classes_class_id FOREIGN KEY (class_id) REFERENCES classes (class_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_class_sessions_rooms_room_id FOREIGN KEY (room_id) REFERENCES rooms (room_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_class_sessions_user_accounts_coach_id FOREIGN KEY (coach_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
                );

                CREATE TABLE seat_holds (
                    hold_id uuid NOT NULL,
                    class_id integer NOT NULL,
                    member_id uuid NOT NULL,
                    invoice_id uuid,
                    expires_at_utc timestamp with time zone NOT NULL,
                    status integer NOT NULL,
                    created_at timestamp with time zone NOT NULL,
                    CONSTRAINT pk_seat_holds PRIMARY KEY (hold_id),
                    CONSTRAINT fk_seat_holds_classes_class_id FOREIGN KEY (class_id) REFERENCES classes (class_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_seat_holds_invoices_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices (invoice_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_seat_holds_user_accounts_member_id FOREIGN KEY (member_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
                );

                CREATE TABLE enrollments (
                    enrollment_id uuid NOT NULL,
                    class_id integer NOT NULL,
                    member_id uuid NOT NULL,
                    invoice_item_id uuid,
                    status integer NOT NULL,
                    enrolled_at timestamp with time zone NOT NULL,
                    ended_at timestamp with time zone,
                    source_enrollment_id uuid,
                    CONSTRAINT pk_enrollments PRIMARY KEY (enrollment_id),
                    CONSTRAINT fk_enrollments_classes_class_id FOREIGN KEY (class_id) REFERENCES classes (class_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_enrollments_enrollments_source_enrollment_id FOREIGN KEY (source_enrollment_id) REFERENCES enrollments (enrollment_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_enrollments_invoice_items_invoice_item_id FOREIGN KEY (invoice_item_id) REFERENCES invoice_items (item_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_enrollments_user_accounts_member_id FOREIGN KEY (member_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
                );

                CREATE TABLE attendances (
                    attendance_id uuid NOT NULL,
                    enrollment_id uuid NOT NULL,
                    session_id uuid NOT NULL,
                    status integer NOT NULL,
                    recorded_by_user_id uuid NOT NULL,
                    recorded_at timestamp with time zone NOT NULL,
                    last_modified_at timestamp with time zone,
                    CONSTRAINT pk_attendances PRIMARY KEY (attendance_id),
                    CONSTRAINT fk_attendances_class_sessions_session_id FOREIGN KEY (session_id) REFERENCES class_sessions (session_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_attendances_enrollments_enrollment_id FOREIGN KEY (enrollment_id) REFERENCES enrollments (enrollment_id) ON DELETE RESTRICT,
                    CONSTRAINT fk_attendances_user_accounts_recorded_by_user_id FOREIGN KEY (recorded_by_user_id) REFERENCES user_accounts (user_id) ON DELETE RESTRICT
                );

                CREATE INDEX ix_classes_coach_id ON classes (coach_id);
                CREATE UNIQUE INDEX ix_classes_code ON classes (code);
                CREATE INDEX ix_classes_default_room_id ON classes (default_room_id);
                CREATE INDEX ix_classes_sport_id_status ON classes (sport_id, status);
                CREATE INDEX ix_classes_status ON classes (status);
                CREATE UNIQUE INDEX ix_class_schedule_rules_class_id_day_of_week_start_time_local ON class_schedule_rules (class_id, day_of_week, start_time_local);
                CREATE UNIQUE INDEX ix_class_sessions_class_id_session_no ON class_sessions (class_id, session_no);
                CREATE INDEX ix_class_sessions_coach_id_start_at_utc ON class_sessions (coach_id, start_at_utc);
                CREATE INDEX ix_class_sessions_rescheduled_from_session_id ON class_sessions (rescheduled_from_session_id);
                CREATE INDEX ix_class_sessions_room_id ON class_sessions (room_id);
                CREATE INDEX ix_class_sessions_start_at_utc_status ON class_sessions (start_at_utc, status);
                CREATE INDEX ix_seat_holds_invoice_id ON seat_holds (invoice_id);
                CREATE INDEX ix_seat_holds_member_id ON seat_holds (member_id);
                CREATE INDEX ix_seat_holds_status_expires_at_utc ON seat_holds (status, expires_at_utc);
                CREATE UNIQUE INDEX ux_seat_holds_class_member_active ON seat_holds (class_id, member_id) WHERE status = 0;
                CREATE INDEX ix_enrollments_member_id_status ON enrollments (member_id, status);
                CREATE INDEX ix_enrollments_source_enrollment_id ON enrollments (source_enrollment_id);
                CREATE UNIQUE INDEX ux_enrollments_class_member_confirmed ON enrollments (class_id, member_id) WHERE status = 0;
                CREATE UNIQUE INDEX ux_enrollments_invoice_item ON enrollments (invoice_item_id) WHERE invoice_item_id IS NOT NULL;
                CREATE UNIQUE INDEX ix_attendances_enrollment_id_session_id ON attendances (enrollment_id, session_id);
                CREATE INDEX ix_attendances_recorded_by_user_id ON attendances (recorded_by_user_id);
                CREATE INDEX ix_attendances_session_id ON attendances (session_id);
                """);

            // Quan hệ huấn luyện ClassBased mới trỏ tới lớp mới; giá trị cũ đã được gỡ khỏi cột (xem legacy_relationship_class_links).
            migrationBuilder.Sql(
                """
                ALTER TABLE coach_member_relationships
                    ADD CONSTRAINT fk_coach_member_relationships_classes_class_id
                    FOREIGN KEY (class_id) REFERENCES classes (class_id) ON DELETE RESTRICT;
                """);

            migrationBuilder.AddColumn<DateTime>(
                name: "check_out_time",
                table: "gym_checkins",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "checked_out_by_user_id",
                table: "gym_checkins",
                type: "uuid",
                nullable: true);

            migrationBuilder.InsertData(
                table: "system_settings",
                columns: new[] { "key", "description", "updated_at", "updated_by_user_id", "value" },
                values: new object[,]
                {
                    { "class.threshold_days_before_start", "BR-119 — Đánh giá ngưỡng hoàn vốn của khóa trước buổi đầu bao nhiêu ngày.", new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc), null, "3" },
                    { "class.threshold_response_hours", "BR-120 — Số giờ Member được trả lời khi khóa học có nguy cơ không đủ ngưỡng.", new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc), null, "48" },
                    { "hold.minutes", "BR-115 — Số phút giữ chỗ và thanh toán tối đa khi checkout.", new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc), null, "15" }
                });

            migrationBuilder.CreateIndex(
                name: "ix_gym_checkins_checked_out_by_user_id",
                table: "gym_checkins",
                column: "checked_out_by_user_id");

            migrationBuilder.AddForeignKey(
                name: "fk_gym_checkins_user_accounts_checked_out_by_user_id",
                table: "gym_checkins",
                column: "checked_out_by_user_id",
                principalTable: "user_accounts",
                principalColumn: "user_id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_gym_checkins_user_accounts_checked_out_by_user_id",
                table: "gym_checkins");

            migrationBuilder.DropIndex(
                name: "ix_gym_checkins_checked_out_by_user_id",
                table: "gym_checkins");

            migrationBuilder.DeleteData(table: "system_settings", keyColumn: "key", keyValue: "class.threshold_days_before_start");
            migrationBuilder.DeleteData(table: "system_settings", keyColumn: "key", keyValue: "class.threshold_response_hours");
            migrationBuilder.DeleteData(table: "system_settings", keyColumn: "key", keyValue: "hold.minutes");

            migrationBuilder.DropColumn(name: "check_out_time", table: "gym_checkins");
            migrationBuilder.DropColumn(name: "checked_out_by_user_id", table: "gym_checkins");

            migrationBuilder.Sql(
                """
                ALTER TABLE coach_member_relationships DROP CONSTRAINT fk_coach_member_relationships_classes_class_id;

                DROP TABLE attendances;
                DROP TABLE enrollments;
                DROP TABLE seat_holds;
                DROP TABLE class_sessions;
                DROP TABLE class_schedule_rules;
                DROP TABLE classes;

                DO $$
                DECLARE r record;
                BEGIN
                    FOR r IN
                        SELECT indexname FROM pg_indexes
                        WHERE schemaname = current_schema()
                          AND tablename IN ('legacy_classes', 'legacy_class_recurrences', 'legacy_class_sessions', 'legacy_enrollments', 'legacy_attendances')
                    LOOP
                        EXECUTE format('ALTER INDEX %I RENAME TO %I', r.indexname, substr(r.indexname, 8));
                    END LOOP;

                    FOR r IN
                        SELECT s.relname AS seq
                        FROM pg_class s
                        JOIN pg_depend d ON d.objid = s.oid AND d.deptype IN ('a', 'i')
                        JOIN pg_class t ON t.oid = d.refobjid
                        WHERE s.relkind = 'S'
                          AND t.relname IN ('legacy_classes', 'legacy_class_recurrences', 'legacy_class_sessions', 'legacy_enrollments', 'legacy_attendances')
                    LOOP
                        EXECUTE format('ALTER SEQUENCE %I RENAME TO %I', r.seq, substr(r.seq, 8));
                    END LOOP;
                END $$;

                ALTER TABLE legacy_classes RENAME TO classes;
                ALTER TABLE legacy_class_recurrences RENAME TO class_recurrences;
                ALTER TABLE legacy_class_sessions RENAME TO class_sessions;
                ALTER TABLE legacy_enrollments RENAME TO enrollments;
                ALTER TABLE legacy_attendances RENAME TO attendances;

                UPDATE coach_member_relationships r
                SET class_id = l.legacy_class_id
                FROM legacy_relationship_class_links l
                WHERE r.relationship_id = l.relationship_id;

                DROP TABLE legacy_relationship_class_links;

                ALTER TABLE coach_member_relationships
                    ADD CONSTRAINT fk_coach_member_relationships_classes_class_id
                    FOREIGN KEY (class_id) REFERENCES classes (class_id) ON DELETE RESTRICT;
                """);
        }
    }
}
