// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportHub.API.Persistence;

#nullable disable

namespace SportHub.API.Migrations
{
    [DbContext(typeof(SportHubDbContext))]
    partial class SportHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportHub.AI.Domain.Entities.AiLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InputPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_payload");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_type");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LogId")
                        .HasName("pk_ai_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_logs_user_id");

                    b.ToTable("ai_logs", (string)null);
                });

            modelBuilder.Entity("SportHub.Audit.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<string>("TargetEntity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_entity");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AuditId")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<int>("RoleName")
                        .HasColumnType("integer")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("pk_roles");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_role_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = 0
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = 1
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = 2
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = 3
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = 4
                        });
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("UserId")
                        .HasName("pk_user_accounts");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_accounts_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_accounts_role_id");

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.UserCredential", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("UserId")
                        .HasName("pk_user_credentials");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.UserExternalLogin", b =>
                {
                    b.Property<Guid>("ExternalLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("external_login_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_user_id");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ExternalLoginId")
                        .HasName("pk_user_external_logins");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_external_logins_provider_provider_user_id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_user_external_logins_user_id_provider");

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("UserId")
                        .HasName("pk_user_profiles");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_phone")
                        .HasFilter("phone IS NOT NULL");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("SportHub.Membership.Domain.Entities.MemberPackage", b =>
                {
                    b.Property<Guid>("MemberPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("member_package_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    b.Property<int?>("RemainingSessions")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_sessions");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("MemberPackageId")
                        .HasName("pk_member_packages");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_member_packages_member_id");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("ix_member_packages_package_id");

                    b.ToTable("member_packages", null, t =>
                        {
                            t.HasCheckConstraint("CK_member_packages_remaining_sessions_non_negative", "remaining_sessions IS NULL OR remaining_sessions >= 0");
                        });
                });

            modelBuilder.Entity("SportHub.Membership.Domain.Entities.MemberTrainingProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer")
                        .HasColumnName("experience_level");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProfileId")
                        .HasName("pk_member_training_profiles");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_member_training_profiles_member_id");

                    b.ToTable("member_training_profiles", (string)null);
                });

            modelBuilder.Entity("SportHub.Membership.Domain.Entities.MembershipPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("package_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PackageId"));

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("price");

                    b.Property<int?>("SessionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("session_limit");

                    b.HasKey("PackageId")
                        .HasName("pk_membership_packages");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_membership_packages_name");

                    b.ToTable("membership_packages", (string)null);
                });

            modelBuilder.Entity("SportHub.Notification.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<int>("Channel")
                        .HasColumnType("integer")
                        .HasColumnName("channel");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid?>("SourceEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entity_id");

                    b.Property<int>("SourceEventType")
                        .HasColumnType("integer")
                        .HasColumnName("source_event_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("SportHub.Payment.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_user_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid?>("MemberPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_package_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("total_amount");

                    b.HasKey("InvoiceId")
                        .HasName("pk_invoices");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_invoice_number");

                    b.HasIndex("IssuedByUserId")
                        .HasDatabaseName("ix_invoices_issued_by_user_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_invoices_member_id");

                    b.HasIndex("MemberPackageId")
                        .HasDatabaseName("ix_invoices_member_package_id");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("SportHub.Payment.Domain.Entities.InvoiceItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<int>("RelatedEntityType")
                        .HasColumnType("integer")
                        .HasColumnName("related_entity_type");

                    b.HasKey("ItemId")
                        .HasName("pk_invoice_items");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_items_invoice_id");

                    b.ToTable("invoice_items", (string)null);
                });

            modelBuilder.Entity("SportHub.Payment.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("amount");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("ReceivedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("received_by_user_id");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("text")
                        .HasColumnName("reference_code");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("PaymentId")
                        .HasName("pk_payments");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.HasIndex("ReceivedByUserId")
                        .HasDatabaseName("ix_payments_received_by_user_id");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("SportHub.Payment.Domain.Entities.PaymentAdjustment", b =>
                {
                    b.Property<Guid>("AdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("adjustment_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18)
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("AdjustmentId")
                        .HasName("pk_payment_adjustments");

                    b.HasIndex("ApprovedByUserId")
                        .HasDatabaseName("ix_payment_adjustments_approved_by_user_id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payment_adjustments_invoice_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_payment_adjustments_payment_id");

                    b.HasIndex("RequestedByUserId")
                        .HasDatabaseName("ix_payment_adjustments_requested_by_user_id");

                    b.ToTable("payment_adjustments", (string)null);
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_id");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<Guid?>("CheckedInByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("checked_in_by_user_id");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("AttendanceId")
                        .HasName("pk_attendances");

                    b.HasIndex("CheckedInByUserId")
                        .HasDatabaseName("ix_attendances_checked_in_by_user_id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendances_enrollment_id");

                    b.ToTable("attendances", (string)null);
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid?>("DefaultCoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_coach_id");

                    b.Property<int>("DefaultRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("default_room_id");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discipline");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("ClassId")
                        .HasName("pk_classes");

                    b.HasIndex("DefaultCoachId")
                        .HasDatabaseName("ix_classes_default_coach_id");

                    b.HasIndex("DefaultRoomId")
                        .HasDatabaseName("ix_classes_default_room_id");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.ClassRecurrence", b =>
                {
                    b.Property<int>("RecurrenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recurrence_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecurrenceId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("days_of_week");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<TimeOnly>("EndTimeLocal")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time_local");

                    b.Property<TimeOnly>("StartTimeLocal")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time_local");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("RecurrenceId")
                        .HasName("pk_class_recurrences");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_class_recurrences_class_id");

                    b.ToTable("class_recurrences", (string)null);
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.ClassSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<int>("ConfirmedCount")
                        .HasColumnType("integer")
                        .HasColumnName("confirmed_count");

                    b.Property<DateTime>("EndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at_utc");

                    b.Property<int?>("RecurrenceId")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence_id");

                    b.Property<Guid?>("RescheduledFromSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("rescheduled_from_session_id");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("SessionId")
                        .HasName("pk_class_sessions");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_class_sessions_class_id");

                    b.HasIndex("CoachId")
                        .HasDatabaseName("ix_class_sessions_coach_id");

                    b.HasIndex("RecurrenceId")
                        .HasDatabaseName("ix_class_sessions_recurrence_id");

                    b.HasIndex("RescheduledFromSessionId")
                        .HasDatabaseName("ix_class_sessions_rescheduled_from_session_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_class_sessions_room_id");

                    b.ToTable("class_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_class_sessions_confirmed_count_within_capacity", "confirmed_count >= 0 AND confirmed_count <= capacity");
                        });
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_user_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("MemberPackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_package_id");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("EnrollmentId")
                        .HasName("pk_enrollments");

                    b.HasIndex("CancelledByUserId")
                        .HasDatabaseName("ix_enrollments_cancelled_by_user_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_enrollments_member_id");

                    b.HasIndex("MemberPackageId")
                        .HasDatabaseName("ix_enrollments_member_package_id");

                    b.HasIndex("SessionId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollments_session_id_member_id")
                        .HasFilter("status = 0");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("RoomId")
                        .HasName("pk_rooms");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_rooms_name");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("SportHub.Training.Domain.Entities.CoachMemberRelationship", b =>
                {
                    b.Property<Guid>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("relationship_id");

                    b.Property<int?>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("RelationshipId")
                        .HasName("pk_coach_member_relationships");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_coach_member_relationships_class_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_coach_member_relationships_member_id");

                    b.HasIndex("CoachId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_coach_member_relationships_coach_id_member_id")
                        .HasFilter("status = 0");

                    b.ToTable("coach_member_relationships", (string)null);
                });

            modelBuilder.Entity("SportHub.Training.Domain.Entities.WorkoutPlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("RelationshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("relationship_id");

                    b.HasKey("PlanId")
                        .HasName("pk_workout_plans");

                    b.HasIndex("CoachId")
                        .HasDatabaseName("ix_workout_plans_coach_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_workout_plans_member_id");

                    b.HasIndex("RelationshipId")
                        .HasDatabaseName("ix_workout_plans_relationship_id");

                    b.ToTable("workout_plans", (string)null);
                });

            modelBuilder.Entity("SportHub.Training.Domain.Entities.WorkoutPlanItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Exercise")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exercise");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("reps");

                    b.Property<int>("Sets")
                        .HasColumnType("integer")
                        .HasColumnName("sets");

                    b.HasKey("ItemId")
                        .HasName("pk_workout_plan_items");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_workout_plan_items_plan_id");

                    b.ToTable("workout_plan_items", (string)null);
                });

            modelBuilder.Entity("SportHub.Training.Domain.Entities.WorkoutResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<string>("CoachComment")
                        .HasColumnType("text")
                        .HasColumnName("coach_comment");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<string>("ProgressNote")
                        .HasColumnType("text")
                        .HasColumnName("progress_note");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("ResultId")
                        .HasName("pk_workout_results");

                    b.HasIndex("CoachId")
                        .HasDatabaseName("ix_workout_results_coach_id");

                    b.HasIndex("EnrollmentId")
                        .HasDatabaseName("ix_workout_results_enrollment_id");

                    b.ToTable("workout_results", (string)null);
                });

            modelBuilder.Entity("SportHub.AI.Domain.Entities.AiLog", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ai_logs_user_accounts_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Audit.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_user_accounts_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.UserAccount", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.Role", "Role")
                        .WithMany("UserAccounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_accounts_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.UserCredential", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "UserAccount")
                        .WithOne("Credential")
                        .HasForeignKey("SportHub.Identity.Domain.Entities.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_credentials_user_accounts_user_id");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "UserAccount")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_external_logins_user_accounts_user_id");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "UserAccount")
                        .WithOne("Profile")
                        .HasForeignKey("SportHub.Identity.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_user_accounts_user_id");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("SportHub.Membership.Domain.Entities.MemberPackage", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_packages_user_accounts_member_id");

                    b.HasOne("SportHub.Membership.Domain.Entities.MembershipPackage", "Package")
                        .WithMany("MemberPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_packages_membership_packages_package_id");

                    b.Navigation("Member");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("SportHub.Membership.Domain.Entities.MemberTrainingProfile", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_member_training_profiles_user_accounts_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SportHub.Notification.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_user_accounts_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportHub.Payment.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "IssuedByUser")
                        .WithMany()
                        .HasForeignKey("IssuedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_user_accounts_issued_by_user_id");

                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_user_accounts_member_id");

                    b.HasOne("SportHub.Membership.Domain.Entities.MemberPackage", "MemberPackage")
                        .WithMany()
                        .HasForeignKey("MemberPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invoices_member_packages_member_package_id");

                    b.Navigation("IssuedByUser");

                    b.Navigation("Member");

                    b.Navigation("MemberPackage");
                });

            modelBuilder.Entity("SportHub.Payment.Domain.Entities.InvoiceItem", b =>
                {
                    b.HasOne("SportHub.Payment.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_items_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("SportHub.Payment.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SportHub.Payment.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "ReceivedByUser")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_user_accounts_received_by_user_id");

                    b.Navigation("Invoice");

                    b.Navigation("ReceivedByUser");
                });

            modelBuilder.Entity("SportHub.Payment.Domain.Entities.PaymentAdjustment", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payment_adjustments_user_accounts_approved_by_user_id");

                    b.HasOne("SportHub.Payment.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Adjustments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_adjustments_invoices_invoice_id");

                    b.HasOne("SportHub.Payment.Domain.Entities.Payment", "Payment")
                        .WithMany("Adjustments")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payment_adjustments_payments_payment_id");

                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_adjustments_user_accounts_requested_by_user_id");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Invoice");

                    b.Navigation("Payment");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "CheckedInByUser")
                        .WithMany()
                        .HasForeignKey("CheckedInByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attendances_user_accounts_checked_in_by_user_id");

                    b.HasOne("SportHub.Scheduling.Domain.Entities.Enrollment", "Enrollment")
                        .WithOne("Attendance")
                        .HasForeignKey("SportHub.Scheduling.Domain.Entities.Attendance", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_enrollments_enrollment_id");

                    b.Navigation("CheckedInByUser");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.Class", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "DefaultCoach")
                        .WithMany()
                        .HasForeignKey("DefaultCoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_classes_user_accounts_default_coach_id");

                    b.HasOne("SportHub.Scheduling.Domain.Entities.Room", "DefaultRoom")
                        .WithMany("Classes")
                        .HasForeignKey("DefaultRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_classes_rooms_default_room_id");

                    b.Navigation("DefaultCoach");

                    b.Navigation("DefaultRoom");
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.ClassRecurrence", b =>
                {
                    b.HasOne("SportHub.Scheduling.Domain.Entities.Class", "Class")
                        .WithMany("Recurrences")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_recurrences_classes_class_id");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.ClassSession", b =>
                {
                    b.HasOne("SportHub.Scheduling.Domain.Entities.Class", "Class")
                        .WithMany("Sessions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_sessions_classes_class_id");

                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_sessions_user_accounts_coach_id");

                    b.HasOne("SportHub.Scheduling.Domain.Entities.ClassRecurrence", "Recurrence")
                        .WithMany("Sessions")
                        .HasForeignKey("RecurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_class_sessions_class_recurrences_recurrence_id");

                    b.HasOne("SportHub.Scheduling.Domain.Entities.ClassSession", "RescheduledFromSession")
                        .WithMany()
                        .HasForeignKey("RescheduledFromSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_class_sessions_class_sessions_rescheduled_from_session_id");

                    b.HasOne("SportHub.Scheduling.Domain.Entities.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_class_sessions_rooms_room_id");

                    b.Navigation("Class");

                    b.Navigation("Coach");

                    b.Navigation("Recurrence");

                    b.Navigation("RescheduledFromSession");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_enrollments_user_accounts_cancelled_by_user_id");

                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_user_accounts_member_id");

                    b.HasOne("SportHub.Membership.Domain.Entities.MemberPackage", "MemberPackage")
                        .WithMany()
                        .HasForeignKey("MemberPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_member_packages_member_package_id");

                    b.HasOne("SportHub.Scheduling.Domain.Entities.ClassSession", "Session")
                        .WithMany("Enrollments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_class_sessions_session_id");

                    b.Navigation("CancelledByUser");

                    b.Navigation("Member");

                    b.Navigation("MemberPackage");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SportHub.Training.Domain.Entities.CoachMemberRelationship", b =>
                {
                    b.HasOne("SportHub.Scheduling.Domain.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_coach_member_relationships_classes_class_id");

                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coach_member_relationships_user_accounts_coach_id");

                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_coach_member_relationships_user_accounts_member_id");

                    b.Navigation("Class");

                    b.Navigation("Coach");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SportHub.Training.Domain.Entities.WorkoutPlan", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_plans_user_accounts_coach_id");

                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_plans_user_accounts_member_id");

                    b.HasOne("SportHub.Training.Domain.Entities.CoachMemberRelationship", "Relationship")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_plans_coach_member_relationships_relationship_id");

                    b.Navigation("Coach");

                    b.Navigation("Member");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("SportHub.Training.Domain.Entities.WorkoutPlanItem", b =>
                {
                    b.HasOne("SportHub.Training.Domain.Entities.WorkoutPlan", "Plan")
                        .WithMany("Items")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workout_plan_items_workout_plans_plan_id");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SportHub.Training.Domain.Entities.WorkoutResult", b =>
                {
                    b.HasOne("SportHub.Identity.Domain.Entities.UserAccount", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_results_user_accounts_coach_id");

                    b.HasOne("SportHub.Scheduling.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workout_results_enrollments_enrollment_id");

                    b.Navigation("Coach");

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("SportHub.Identity.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("ExternalLogins");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("SportHub.Membership.Domain.Entities.MembershipPackage", b =>
                {
                    b.Navigation("MemberPackages");
                });

            modelBuilder.Entity("SportHub.Payment.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SportHub.Payment.Domain.Entities.Payment", b =>
                {
                    b.Navigation("Adjustments");
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.Class", b =>
                {
                    b.Navigation("Recurrences");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.ClassRecurrence", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.ClassSession", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.Enrollment", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("SportHub.Scheduling.Domain.Entities.Room", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SportHub.Training.Domain.Entities.CoachMemberRelationship", b =>
                {
                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("SportHub.Training.Domain.Entities.WorkoutPlan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
