"use client";
import { pagedItems } from "@/lib/paged";
import { useState } from "react";
import { AsyncSection, Card, Field, Pager, StatusChip } from "@/components/ui";
import { api, downloadFile } from "@/lib/apiClient";
import { useApi } from "@/lib/useApi";
import { useLanguage } from "@/lib/language";
import { MutationFeedback, useMutation } from "@/features/operations";
import { reportsApi, type ReportFilters } from "./api";
const columnsByType: Record<string, string[]> = {
 REVENUE_DIMENSIONS: ["source", "sportId", "sportName", "externalCoachId", "collectedAmount", "legacyCashCollected", "pointsRedeemed", "pointsRedeemedVnd"],
 COURT_RENTAL_REVENUE: ["source", "sportId", "sportName", "externalCoachId", "collectedAmount", "legacyCashCollected", "pointsRedeemed", "pointsRedeemedVnd"],
 REVENUE_SUMMARY: ["fromDate", "toDate", "collectedAmount", "legacyCashCollected", "reconciliationCashCollected", "pointsRedeemedVnd", "pointsIssued", "managerPointAdjustment", "outstandingPoints"],
 CLASS_ENROLLMENT: ["classId", "name", "sportName", "capacity", "confirmedCount", "activeHoldCount", "availableSeats", "fillRatio", "breakEvenThreshold", "thresholdStatus"],
 MEMBERSHIP_PERIOD: ["fromDate", "toDate", "newMembers", "activeMembersAtPeriodEnd"],
};
export function ReportExportPanel({ filters }: { filters: ReportFilters }) {
 const { t } = useLanguage(); const l = t.staffWork; const [type, setType] = useState("REVENUE_DIMENSIONS"); const [columns, setColumns] = useState<string[]>([]); const [format, setFormat] = useState("Csv"); const [page, setPage] = useState(1); const mutation = useMutation(); const state = useApi(signal => reportsApi.exports(page, signal), [page]);
 const dimensional = type === "REVENUE_DIMENSIONS" || type === "COURT_RENTAL_REVENUE";
 const labels: Record<string, string> = { REVENUE_DIMENSIONS: l.dimensions, COURT_RENTAL_REVENUE: l.rentals, REVENUE_SUMMARY: l.points, CLASS_ENROLLMENT: l.enrollment, MEMBERSHIP_PERIOD: l.membership };
 const columnLabels: Record<string, string> = { source: l.source, sportId: `${l.sport} ID`, sportName: l.sport, externalCoachId: l.externalCoach, collectedAmount: l.cash, legacyCashCollected: l.legacyCash, reconciliationCashCollected: l.reconciliationCash, pointsRedeemed: l.points, pointsRedeemedVnd: l.redeemed, pointsIssued: l.issued, managerPointAdjustment: l.adjusted, outstandingPoints: l.outstanding, fromDate: l.from, toDate: l.to, classId: "ID", name: l.title, capacity: l.capacity, confirmedCount: l.confirmed, activeHoldCount: l.holds, availableSeats: l.available, fillRatio: l.fillRatio, breakEvenThreshold: l.threshold, thresholdStatus: l.status, newMembers: l.newMembers, activeMembersAtPeriodEnd: l.activeMembers };
 return <Card title={l.export}><form className="form" onSubmit={async e => { e.preventDefault(); if (await mutation.run(() => api.post("/api/reports/exports", { reportType: type, fromDate: filters.fromDate, toDate: filters.toDate, columns, format, sportId: dimensional || type === "CLASS_ENROLLMENT" ? (filters.sportId ? Number(filters.sportId) : null) : null, source: dimensional ? (type === "COURT_RENTAL_REVENUE" ? "RENTAL" : filters.source || null) : null, externalCoachId: dimensional ? filters.externalCoachId || null : null }))) state.reload(); }}><Field label={l.exportType}><select value={type} onChange={e => { setType(e.target.value); setColumns([]); }}>{Object.keys(columnsByType).map(key => <option key={key} value={key}>{labels[key]}</option>)}</select></Field><p>{filters.fromDate} – {filters.toDate}{(dimensional || type === "CLASS_ENROLLMENT") && ` · ${l.sport}: ${filters.sportId || l.all}`}{dimensional && ` · ${l.source}: ${type === "COURT_RENTAL_REVENUE" ? l.rentals : filters.source || l.all} · ${l.externalCoach}: ${filters.externalCoachId || l.all}`}</p>{type === "REVENUE_SUMMARY" && <p>{l.globalPoints}</p>}<fieldset><legend>{l.columns}</legend>{columnsByType[type].map(c => <label key={c}><input type="checkbox" checked={columns.includes(c)} onChange={e => setColumns(e.target.checked ? [...columns, c] : columns.filter(x => x !== c))}/>{columnLabels[c] ?? c}</label>)}</fieldset><Field label={l.format}><select value={format} onChange={e => setFormat(e.target.value)}><option value="Csv">CSV</option><option value="Pdf">PDF</option></select></Field><button className="btn" disabled={mutation.busy || !columns.length}>{l.export}</button></form><MutationFeedback mutation={mutation}/><h3>{l.exportHistory}</h3><button className="btn btn--secondary" onClick={state.reload}>{l.refresh}</button><AsyncSection state={state}>{data => <>{pagedItems(data).map(r => <article key={r.reportExportId}><p>{labels[r.reportType] ?? r.reportType} · <StatusChip value={r.status}/></p>{r.failureReason && <p role="alert">{r.failureReason}</p>}{r.status === "COMPLETED" && <button className="btn btn--secondary" disabled={mutation.busy} onClick={() => mutation.run(() => downloadFile(`/api/reports/exports/${r.reportExportId}/download`, `${r.reportType}.${r.format.toLowerCase()}`))}>{l.download}</button>}{r.status === "FAILED" && <button className="btn btn--secondary" disabled={mutation.busy} onClick={async () => { if (await mutation.run(() => api.post(`/api/reports/exports/${r.reportExportId}/retry`))) state.reload(); }}>{t.common.retry}</button>}</article>)}<Pager page={data.page} pageSize={data.pageSize} totalCount={data.totalCount} onChange={setPage}/></>}</AsyncSection></Card>;
}
