"use client";
import { useState } from "react";
import Link from "next/link";
import { AsyncSection, Card, Field, Stat } from "@/components/ui";
import { api } from "@/lib/apiClient";
import { useApi } from "@/lib/useApi";
import { useLanguage } from "@/lib/language";
import { vietnamLocal } from "@/lib/vietnam-time";
import type { SportDto } from "@/lib/types";
import { reportsApi, type ReportFilters } from "./api";
import { RevenueSummary } from "./revenue-summary";
import { PointsReport } from "./points-report";
import { ClassEnrollmentReport } from "./class-enrollment-report";
import { CourtRentalReport } from "./court-rental-report";
import { ReportExportPanel } from "./report-export-panel";
function initialFilters(): ReportFilters { const now = new Date(); const toDate = vietnamLocal(now.toISOString()).slice(0, 10); return { fromDate: toDate.slice(0, 8) + "01", toDate, sportId: "", source: "", externalCoachId: "" }; }
function ReportContent({ filters: f }: { filters: ReportFilters }) { const { t } = useLanguage(); const summary = useApi(signal => reportsApi.summary(f, signal), [f]); const dimensions = useApi(signal => reportsApi.dimensions(f, signal), [f]); const rentals = useApi(signal => reportsApi.dimensions({ ...f, source: "RENTAL" }, signal), [f]); const classes = useApi(signal => reportsApi.classes(f, signal), [f]); const membership = useApi(signal => reportsApi.membership(f, signal), [f]); return <><AsyncSection state={dimensions}>{r => <RevenueSummary report={r}/>}</AsyncSection><AsyncSection state={rentals}>{r => <CourtRentalReport report={r}/>}</AsyncSection><AsyncSection state={classes}>{r => <ClassEnrollmentReport report={r}/>}</AsyncSection><AsyncSection state={summary}>{r => <PointsReport report={r}/>}</AsyncSection><Card title={t.staffWork.membership}><AsyncSection state={membership}>{r => <div className="stats-grid"><Stat label={t.staffWork.newMembers} value={r.newMembers}/><Stat label={t.staffWork.activeMembers} value={r.activeMembersAtPeriodEnd}/></div>}</AsyncSection></Card><ReportExportPanel filters={f}/></>; }
export function Reports() { const { t } = useLanguage(); const l = t.staffWork; const [filters, setFilters] = useState(initialFilters); const [draft, setDraft] = useState(filters); const [error, setError] = useState(false); const sports = useApi(signal => api.get<SportDto[]>("/api/manager/sports", { signal }), []); return <><Card><form className="form" onSubmit={e => { e.preventDefault(); const days = (Date.parse(draft.toDate) - Date.parse(draft.fromDate)) / 86400000; if (!Number.isFinite(days) || days < 0 || days > 366) { setError(true); return; } setError(false); setFilters({ ...draft }); }}><div className="form-grid"><Field label={l.from}><input type="date" required value={draft.fromDate} onChange={e => setDraft({ ...draft, fromDate: e.target.value })}/></Field><Field label={l.to}><input type="date" required value={draft.toDate} onChange={e => setDraft({ ...draft, toDate: e.target.value })}/></Field><AsyncSection state={sports}>{rows => <Field label={l.sport}><select value={draft.sportId} onChange={e => setDraft({ ...draft, sportId: e.target.value })}><option value="">{l.all}</option>{rows.map(s => <option key={s.sportId} value={s.sportId}>{s.name}</option>)}</select></Field>}</AsyncSection><Field label={l.source}><select value={draft.source} onChange={e => setDraft({ ...draft, source: e.target.value })}><option value="">{l.all}</option>{[["MEMBERSHIP", l.sourceMembership], ["PT", l.sourcePt], ["CLASS_PACKAGE", l.sourceClass], ["RENTAL", l.sourceRental], ["RECONCILIATION", l.sourceReconciliation], ["LEGACY_UNCLASSIFIED", l.sourceLegacy]].map(([v, label]) => <option key={v} value={v}>{label}</option>)}</select></Field><Field label={l.externalCoach}><input value={draft.externalCoachId} pattern="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}" onChange={e => setDraft({ ...draft, externalCoachId: e.target.value })}/></Field></div>{error && <p role="alert">{l.dateRange}</p>}<button className="btn">{l.apply}</button></form></Card><ReportContent filters={filters}/></>; }
export function ManagerOverview() { const { t } = useLanguage(); const [f] = useState(initialFilters); const state = useApi(signal => reportsApi.summary(f, signal), [f]); return <><AsyncSection state={state}>{r => <PointsReport report={r}/>}</AsyncSection><Card><div className="btn-row">{[["classes", "classes"], ["pt-sessions", "sessions"], ["pt-change-requests", "requests"], ["points", "wallet"], ["payment-adjustments", "refunds"], ["reports", "reports"]].map(([path, key]) => <Link key={path} className="btn btn--secondary" href={`/manager/${path}`}>{t.staffWork[key as keyof typeof t.staffWork]}</Link>)}</div></Card></>; }
